### PR TITLE
V2Ray/XRay: allow protocol selection

### PR DESCRIPTION
**Pull request by xsm1997**
允许V2Ray/XRay选择协议。

8MYYL}4_GT)ZZM%(PP1J6P9

~~**注意：更新之后配置会变得不兼容，请自行重新配置VMess/VLESS服务器。**~~
**更新：已添加自动迁移脚本，在刷入新固件之后，应该不需要手动重新配置服务器了。**

目前支持V2Ray/XRay的VMess、VLESS、HTTP、Socks、Shadowsocks、Trojan协议，**并未完全测试**，所以建议有需求者使用此pr的patch，经过充分测试后方可合并主线。欢迎回报bug，在我能力范围内我会及时更新。

已测试的功能：使用XRay，VMess、VLESS、Trojan的TCP配置，Trojan的UDP配置，VMess分享链接导入、VMess订阅导入。
其余协议只测试了XRay可以成功加载配置并运行，未做实际的连通性测试。

### CODE REVIEW

**Comment by happy201807** [comment]
Vless ws TLS with Xray core，It can be activated, but cannot be connected

**Comment by xsm1997** [comment]
> Vless ws TLS with Xray core，It can be activated, but cannot be connected

For me, VLESS with ws and TLS works normally on XRay-core.
Please post your config in OpenWRT (/etc/config/shadowsocksr file) and server config of XRay-core for further examination.

**Comment by happy201807** [comment]
Hi, I use this author's firmware for R4S(https://github.com/quintus-lab/NanoPi-R4S-OpenWRT), ws tls vless with Xray core has not been able to work normally. The following is the config of openwrt and the config of server.

OPENWRT:
`config global
	option netflix_proxy '0'
	option threads '0'
	option run_mode 'router'
	option monitor_enable '1'
	option enable_switch '1'
	option switch_time '667'
	option switch_timeout '5'
	option switch_try_count '3'
	option gfwlist_url 'https://cdn.jsdelivr.net/gh/gfwlist/gfwlist/gfwlist.txt'
	option chnroute_url 'https://ispip.clang.cn/all_cn.txt'
	option nfip_url 'https://cdn.jsdelivr.net/gh/QiuSimons/Netflix_IP/getflix.txt'
	option adblock_url 'https://anti-ad.net/anti-ad-for-dnsmasq.conf'
	option pdnsd_enable '0'
	option netflix_server 'same'
	option global_server 'cfg034a8f'
	option dports '2'

config access_control
	option lan_ac_mode '0'
	option router_proxy '1'
	list Interface 'lan'
	list wan_fw_ips '149.154.160.0/20'
	list wan_fw_ips '67.198.55.0/24'
	list wan_fw_ips '91.108.4.0/22'
	list wan_fw_ips '91.108.56.0/22'
	list wan_fw_ips '109.239.140.0/24'



config socks5_proxy
	option socks '0'
	option local_port '1080'

config server_global
	option enable_server '0'

config servers
	option switch_enable '0'
	option alias 'hgc'
	option v2ray_protocol 'vless'
	option server 'Domain'
	option server_port '443'
	option vmess_id 'ID'
	option vless_encryption 'none'
	option transport 'ws'
	option tls '1'
	option tls_host 'Domain'
	option insecure '0'
	option ip 'IP'
	option type 'vless'
	option mux '0'
	option local_port '4321'
	option ws_path '/4ec07871d34/'


`

SERVER:

`{
    "log": {
        "access": "/var/log/xray/access.log",
        "error": "/var/log/xray/error.log",
        "loglevel": "warning"
    },
    "inbounds": [{
		"port":10000,
        "listen": "10.0.1.1",
        "tag": "VLESS-in",
        "protocol": "vless",
        "settings": {
            "clients": [{
				"id":"ID",
                "alterId": 0
            }],
            "decryption": "none"
        },
        "streamSettings": {
            "network": "ws",
            "security": "none",
            "wsSettings": {
		"path":"/4ec07871d34/"
            }
        }
    }],
    "outbounds": [{
            "protocol": "freedom",
            "tag": "direct"
        },
        {
            "protocol": "blackhole",
            "tag": "blocked"
        }
    ],
    "dns": {
        "servers": [
            "https+local://1.1.1.1/dns-query",
            "1.1.1.1",
            "1.0.0.1",
            "8.8.8.8",
            "8.8.4.4",
            "localhost"
        ]
    },
    "routing": {
        "domainStrategy": "AsIs",
        "rules": [{
            "type": "field",
            "inboundTag": [
                "VLESS-in"
            ],
            "outboundTag": "direct"
        }]
    }
}`

**Comment by xsm1997** [comment]
@happy201807 Maybe you should turn on allow insecure option in web config. If you use self-signed certificates or a certificate whose certificate chain is not complete, you should turn the option on.

Can you try if the mainline version (not this pr) works? I did not modify much on the ws and tls part, and as far as I have tested, it works normally.

**Comment by happy201807** [comment]
Yes, you are right, it works now.

**Comment by xsm1997** [comment]
I think it is stable enough to be merged into mainstream. Please let me know if it needs further modifications. @coolsnowwolf

**Comment by xsm1997** [comment]
I added an auto migration script to convert previous config file format to the present. So, there is no need to reconfigurate servers.

**Comment by quintus-lab** [comment]
> I added an auto migration script to convert previous config file format to the present. So, there is no need to reconfigurate servers.

Can you adapte to the new version SSR-Plus? The version 182-5 code files have changed a lot.

**Comment by xsm1997** [comment]
Please let me know it it needs further modification to be merged into mainstream. @coolsnowwolf

**Pull request merged**
