### PR TITLE
shadowsocks-rust: add new package

### PR DESCRIPTION
**Pull request by 1715173329**
How fast ss-rust is (aes-128-gcm, on NanoPi R2S with 1608MHz)?
image

### CODE REVIEW

**Comment by 1715173329** [comment]
Cc: @Mattraks

**Comment by KaneGreen** [comment]
This name of the binary file `sslocal` (rust) is easily confused with `ss-local` (original).
I suggest to rename the rust version to `sslocal-rs` when installing. `-rs` is usually used as a suffix for the rust version in rust community.

**Comment by 1715173329** [comment]
@KaneGreen Keep it as-is.
And ss-libev will be replaced by ss-rust.

**Comment by KaneGreen** [comment]
@1715173329 I think classic ss will be uesd by many people in a long time. Not all ss service providers use AEAD.

**Comment by 1715173329** [comment]
Ah, it's time to drop those wastes.
BTW, I've enabled compatible mode, so those outdated ciphers could be used, although very slow lol

**Comment by KaneGreen** [comment]
If I were you, I'd like to drop classic ss in the time of adding ss-rust

**Pull request merged**
