### PR TITLE
Fix the error that wss cannot connect when only using CDN IP

### LINKED ISSUE #263: 昨晚编译的最新版SSR无法更新GFW等列表
昨晚更新的最新build，无法更新GFW、国内外、AWS列表，均显示更新失败

### LINKED ISSUE #284: 套CF之后VMESS无法使用
image
使用域名地址则能正常使用，其它客户端（passwall、openclash）无此问题

### LINKED ISSUE #287: 新编译版本更新列表错误
QQ截图20201219000218
上一个版本没有问题 ，已经安装了WGET。

### PR DESCRIPTION
**Pull request by Mattraks**
Fix the error that wss cannot connect when only using CDN IP
Fixes #284 
Fix the problem caused by https://github.com/openwrt/packages/pull/14257
Fixes #287 
Fixes #263

### CODE REVIEW

**Comment by coolsnowwolf** [comment]
wget-ssl 改 wget 后便不再兼任潘多拉，请修改

**Comment by coolsnowwolf** [comment]
更好的方法是加一个变量，做 wget-ssl 这个文件位置的判断

**Comment by Mattraks** [comment]
Doesn't Pandorabox have a wget file? The wget file is generated by the soft connection of wget-ssl or wget-nossl

**Comment by Mattraks** [comment]
> wget-ssl 改 wget 后便不再兼任潘多拉，请修改

>更好的方法是加一个变量，做 wget-ssl 这个文件位置的判断



### 加判断完全没有意义,原本就应该使用wget

**Comment by fanck0605** [comment]
> wget-ssl 改 wget 后便不再兼任潘多拉，请修改

@coolsnowwolf 不修改便不再兼容新版 openwrt master

#322

**Pull request merged**
