### PR TITLE
tcping 3 times and return average delay

### PR DESCRIPTION
**Pull request by fonlan**
tcping 3 times and return average delay will be more accurate for server delay

### CODE REVIEW

**Comment by 1715173329** [comment]
以目前的情况来看，这个意义不大

**Comment by fonlan** [comment]
> 以目前的情况来看，这个意义不大

作用确实不大，只是让显示相对准一点而已

**Comment by 1715173329** [comment]
IMO, I don't see the point.
Let's see if somebody else is interested in this.

**Comment by 1715173329** [comment]
well, you made this even more complex, so NAK.

**Pull request closed without merging**
