### PR TITLE
shadowsocks-rust add aarch64, arm, x86_64 support for glibc

### PR DESCRIPTION
**Pull request by bzi-bit**

### CODE REVIEW

**Comment by 1715173329** [comment]
uh god, now it becomes more complex...

**Comment by bzi-bit** [comment]
> 呃，上帝，现在它变得更加复杂...

It might be a lot easier to compile binaries, but I won't

**Comment by bzi-bit** [comment]
> uh god, now it becomes more complex...

It might be a lot easier to compile binaries, but I won't

**Comment by 1715173329** [comment]
> It might be a lot easier to compile binaries, but I won't

rust toolchain on OpenWrt  isn't available yet and the porting progress is really slow.

**Pull request closed without merging**
